<p>Nuestra  escuela se dedica al proveerle a todos los estudiantes con un fundaci&oacute;n  educacional necesaria para lograr &eacute;xito con sus estudios igual que as&iacute; en su  vida.&nbsp; Para poder asegurarle &eacute;xito a su  hijo/a, hemos puesto las metas a un alto nivel que ser&aacute; refeccionado en los que  se ensena en nuestros salones de clase.&nbsp; As&iacute;  como es requerido por leyes y reglas federales y estatales,&nbsp; nuestro progreso &nbsp;as&iacute; a las metas de lectura y matem&aacute;tica para  todos los estudiantes es evaluado anualmente.&nbsp;  Esas escuelas que &nbsp;constantemente &nbsp;no logran con sus metas ser&aacute;n identificadas  como necesitando mejoramiento.<br />
  Nuestra  escuela se ha identificado como necesitando mejoramiento en:&nbsp; LEP Econ&oacute;micamente desaventajados, matem&aacute;tica.<br />
  Seg&uacute;n la  leyes &nbsp;y reglas federales y estatales, &nbsp;estudiantes en &nbsp;escuelas identificadas para mejoramiento, son elegibles  para aplicar para cambio a otra escuela en el distrito que ha logrado con sus  metas acad&eacute;micas.&nbsp; Sin embargo, nuestro  distrito no tiene opciones disponibles viendo que a este tiempo solamente existe  una preparatoria,<br />
  Nuestra  facultad continuamente trabaja para mejorar el proceso educacional y para  proveer una experiencia de calidad para su hijo/a (Asistencia por otros  estudiantes, labs de matem&aacute;tica, p&oacute;liza de Cero, asistencia por los maestros,  labs en Lenguaje, Lectura y ciencias).<br />
  El Involucramiento  por los padres es esencial en nuestros esfuerzos para mejorar.&nbsp; Les invitamos a participar en los siguientes  modos:&nbsp; (Asistencia acad&eacute;mica para los  estudiantes, chequear los grados, involucramiento en las escuelas, club de  Boosters, y otras actividades).&nbsp; Para  involucrarse comun&iacute;quese con la escuela Preparatoria al 436-4721. &nbsp;Si hay preguntas con la atendencia, comun&iacute;quese  con&nbsp; Mrs. Garro en la oficina de  atendencia al 436-4707.</p>
<p>Sinceramente,</p>
<p>Dan Rogers<br />
  Principal<br />
  Preparatoria Minico </p>
